/*
Номер связи формируется таким образом, 11 значный:

1. начальная двоечка (тип = связь)
2. номер базы данных (вид базы данных)
3. номер места - приемника
4. номер места - источника
5. номер связи (по порядку)

например
201000001


Базы данных:

01 Операционный день
02 Вклады
03 Кредиты
04 Удаленный клиент
05 Кредитный клиент
06 Валютный реестр


Офисы:
00 голова
01-08 по таблице офисов
*/

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR) VALUES (201000001, 'Резерв: Опер. день', 101000000, 101000100, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR) VALUES (202000001, 'Резерв: вклады', 102000000, 102000100, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR) VALUES (206000001, 'Резерв: валютный реестр', 106000000, 106000100, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (202010001, 'Резерв: Вклады Бурея', 102010000, 102010100, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (202020001, 'Резерв: Вклады Завитинск', 102020000, 102020100, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (202030001, 'Резерв: Вклады Белогорск', 102030000, 102030100, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (202040001, 'Резерв: Вклады Свободный', 102040000, 102040100, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (202050001, 'Резерв: Вклады Шимановск', 102050000, 102050100, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (202060001, 'Резерв: Вклады Магдагачи', 102060000, 102060100, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (202070001, 'Резерв: Вклады Сковородино', 102070000, 102070100, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (202080001, 'Резерв: Вклады Ерофей', 102080000, 102080100, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (205000001, 'Резерв: Кредитный клиент', 105000000, 105000100, 0, 0, NULL, NULL, NULL, NULL);

--------------------------------------------------------------------------------
-- синхронизация офисов (ID связи, последние две цифры, от 10 до 20)

-- шимановск
INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (206050010, 'Валютный реестр: Шимановск->Благовещенск', 106050000, 106051000, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (202050010, 'Вклады: Шимановск->Благовещенск', 102050000, 102051000, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (205050010, 'Кредитный клиент: Шимановск->Благовещенск', 105050000, 105000000, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (205050002, 'Кредитный клиент: Благовещенск->Шимановск', 105000000, 105050000, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (204050010, 'Удаленный клиент: Шимановск->Благовещенск', 104050000, 104051000, 0, 0, NULL, NULL, NULL, NULL);

-- магдагачи
INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (206060010, 'Валютный реестр: Магдагачи->Благовещенск', 106060000, 106061000, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (202060010, 'Вклады: Магдагачи->Благовещенск', 102060000, 102061000, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (205060010, 'Кредитный клиент: Магдагачи->Благовещенск', 105060000, 105000000, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (205060002, 'Кредитный клиент: Благовещенск->Магдагачи', 105000000, 105060000, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (204060010, 'Удаленный клиент: Магдагачи->Благовещенск', 104060000, 104061000, 0, 0, NULL, NULL, NULL, NULL);

-- сковородино
INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (206070010, 'Валютный реестр: Сковородино->Благовещенск', 106070000, 106071000, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (202070010, 'Вклады: Сковородино->Благовещенск', 102070000, 102071000, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (205070010, 'Кредитный клиент: Сковородино->Благовещенск', 105070000, 105000000, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (204070010, 'Удаленный клиент: Сковородино->Благовещенск', 104070000, 104071000, 0, 0, NULL, NULL, NULL, NULL);

-- ерофей
INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (206080010, 'Валютный реестр: Ерофей->Благовещенск', 106080000, 106081000, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (202080010, 'Вклады: Ерофей->Благовещенск', 102080000, 102081000, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (205080010, 'Кредитный клиент: Ерофей->Благовещенск', 105080000, 105000000, 0, 0, NULL, NULL, NULL, NULL);

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (204080010, 'Удаленный клиент: Ерофей->Благовещенск', 104080000, 104081000, 0, 0, NULL, NULL, NULL, NULL);

--------------------------------------------------------------------------------

-- обратные связи с Благовещенска в офисы

INSERT INTO SYNC_LINK (ID, NAME, PARTICIPANT_FROM, PARTICIPANT_TO, LOG_POSITION, POSITION_UPD_COUNT, LAST_UPDATE_TM, LAST_UPDATE_USER_ID, LAST_UPDATE_CLIENT_ADDR, CONNECT_ADDR)
VALUES (205000028, 'Кредитный клиент: Благовещенск->Ерофей', 105000000, 105080000, 0, 0, NULL, NULL, NULL, NULL);

commit;

