execute procedure sp_sync_arc_init_table('BANK_INFO', 1);
execute procedure sp_sync_arc_init_table('BRON', 1);
execute procedure sp_sync_arc_init_table('CRYPT_CERT', 1);
execute procedure sp_sync_arc_init_table('CRYPT_SETTINGS', 1);
execute procedure sp_sync_arc_init_table('DOC_NAZN', 1);
execute procedure sp_sync_arc_init_table('DOG_PERECH_SPR', 1);
execute procedure sp_sync_arc_init_table('DOKYM', 1, 'DOC_TIME;DOC_STATE;DOCID_ID;DOC_BANK_ID;DOC_PACKET_NAME;DOC_ERR;DOC_BANK_US_ID;DOC_BANKSTATE;DOC_ERR_REASON;');
execute procedure sp_sync_arc_init_table('GR_KLIEN', 1);
execute procedure sp_sync_arc_init_table('GR_SCH', 1);
execute procedure sp_sync_arc_init_table('KLIENT', 1);
execute procedure sp_sync_arc_init_table('KORRESP', 1);
execute procedure sp_sync_arc_init_table('KURS', 1);
execute procedure sp_sync_arc_init_table('PARAM', 1);
execute procedure sp_sync_arc_init_table('RESTR_DESCR', 1);
execute procedure sp_sync_arc_init_table('SCHET', 1, 'SCH_OST');
execute procedure sp_sync_arc_init_table('SCH_OPEN_SCHEMA', 1);
execute procedure sp_sync_arc_init_table('SEARCH', 1);
execute procedure sp_sync_arc_init_table('SIMV_KP', 1);
execute procedure sp_sync_arc_init_table('USERS', 1);
execute procedure sp_sync_arc_init_table('USER_RESTRICTIONS', 1);
execute procedure sp_sync_arc_init_table('VALUTA', 1);
execute procedure sp_sync_arc_init_table('VID_OPER', 1);
