execute procedure sp_sync_arc_init_table('OPER_DNI', 1);
execute procedure sp_sync_arc_init_table('ACCOUNT', 1);
execute procedure sp_sync_arc_init_table('DOGHIST_TYPES', 1);
execute procedure sp_sync_arc_init_table('DOGOVOR', 1);
execute procedure sp_sync_arc_init_table('DOGOVOR_KRLINE', 1);
execute procedure sp_sync_arc_init_table('DOG_CAT_CB', 1);
execute procedure sp_sync_arc_init_table('DOG_CEL', 1);
execute procedure sp_sync_arc_init_table('DOG_GAS_TYPE', 1);
execute procedure sp_sync_arc_init_table('DOG_HISTORY', 1);
execute procedure sp_sync_arc_init_table('DOG_KAT', 1);
execute procedure sp_sync_arc_init_table('DOG_LINKS', 1);
execute procedure sp_sync_arc_init_table('DOG_ORGANIZATION', 1);
execute procedure sp_sync_arc_init_table('DOG_TYPE', 1);
execute procedure sp_sync_arc_init_table('DOG_VID', 1);
execute procedure sp_sync_arc_init_table('DOG_VYDACH', 1);
execute procedure sp_sync_arc_init_table('DOKYM', 1, 'DOC_TIME;DOC_EXPORTED;DOC_OPER_ID;');
execute procedure sp_sync_arc_init_table('DOPOLN', 1);
execute procedure sp_sync_arc_init_table('GASHEN', 1);
--execute procedure sp_sync_arc_init_table('GASH_PLAN', 1);
execute procedure sp_sync_arc_init_table('INSURE_COMPANY', 1);
execute procedure sp_sync_arc_init_table('INSURE_DOG', 1);
execute procedure sp_sync_arc_init_table('INSURE_TYPE', 1);
execute procedure sp_sync_arc_init_table('KLIENT', 1);
execute procedure sp_sync_arc_init_table('KLIENT_KS', 1);
execute procedure sp_sync_arc_init_table('KLIENT_OWN', 1);
execute procedure sp_sync_arc_init_table('PARAM', 1);
execute procedure sp_sync_arc_init_table('PLACES', 1);
execute procedure sp_sync_arc_init_table('RC_SCH', 1);
execute procedure sp_sync_arc_init_table('SCHET', 1, 'SCH_OST;SCH_DPP;');
execute procedure sp_sync_arc_init_table('SCH_DOG', 1);
execute procedure sp_sync_arc_init_table('SCH_OD', 1);
execute procedure sp_sync_arc_init_table('SCH_OD_NAZN', 1);
execute procedure sp_sync_arc_init_table('SEARCH', 1);
execute procedure sp_sync_arc_init_table('SIMV_KP', 1);
execute procedure sp_sync_arc_init_table('SVAJZ', 1);
execute procedure sp_sync_arc_init_table('SVAJZ_TYPE', 1);
execute procedure sp_sync_arc_init_table('SYS_SCHET', 1);
execute procedure sp_sync_arc_init_table('SYS_SCHET_TYPE', 1);
execute procedure sp_sync_arc_init_table('USERS', 1);
execute procedure sp_sync_arc_init_table('VALIDATE_DAY', 1);
execute procedure sp_sync_arc_init_table('VID_DOC', 1);
execute procedure sp_sync_arc_init_table('VID_KLIENT', 1);
execute procedure sp_sync_arc_init_table('VYDACH', 1);


