execute procedure sp_sync_arc_init_table('ADDR', 1);
execute procedure sp_sync_arc_init_table('ADDR_TYPES', 1);
execute procedure sp_sync_arc_init_table('BAL_1', 1);
execute procedure sp_sync_arc_init_table('BAL_2', 1);
execute procedure sp_sync_arc_init_table('BNK', 1, 'BNK_REVISED');
execute procedure sp_sync_arc_init_table('BNK_REG', 1);
execute procedure sp_sync_arc_init_table('BRON', 1);
execute procedure sp_sync_arc_init_table('CONTACT', 1);
execute procedure sp_sync_arc_init_table('COUNTRY', 1);
execute procedure sp_sync_arc_init_table('DOC_TAX', 1);
execute procedure sp_sync_arc_init_table('DOC_TAX_SPR', 1);
execute procedure sp_sync_arc_init_table('DOC_VB', 1, 'DOC_TIME;');
execute procedure sp_sync_arc_init_table('DOKYM', 1, 'DOC_TIME;DOC_OTL;DOC_OTPR;DOC_PODT;DOC_PROV;DOC_CHANGED;DOC_US_CHANGE;DOC_CHANGECOUNT;DOC_OTPR_COUNT;DOC_CLOSD_EDIT;DOC_DAT_FIX;');
execute procedure sp_sync_arc_init_table('DOKYM_EXP_CONTENTS', 1, 'DEP_STATE;');
execute procedure sp_sync_arc_init_table('DOKYM_EXP_PACKETS', 1, 'PACKET_STATE;');
execute procedure sp_sync_arc_init_table('DOKYM_IMP_CONTENTS', 1);
execute procedure SP_SYNC_ARC_INIT_TABLE('DOKYM_IMP_PACKETS', 1);
execute procedure SP_SYNC_ARC_INIT_TABLE('DOKYM_VB', 1, 'DOC_TIME;');
execute procedure SP_SYNC_ARC_INIT_TABLE('GR_KLIEN', 1);
execute procedure sp_sync_arc_init_table('GR_OBSL', 1);
execute procedure sp_sync_arc_init_table('GR_SCH', 1);
execute procedure sp_sync_arc_init_table('KLIENT', 1, 'TKB;');
execute procedure sp_sync_arc_init_table('KLIENT_JUR', 1);
execute procedure sp_sync_arc_init_table('KORESP', 1);
execute procedure sp_sync_arc_init_table('LEGAL', 1);
execute procedure sp_sync_arc_init_table('LEG_DBF', 1);
execute procedure sp_sync_arc_init_table('LEG_DBF2', 1);
execute procedure sp_sync_arc_init_table('LEG_SPR', 1);
execute procedure sp_sync_arc_init_table('NAME_ARS', 1);
execute procedure sp_sync_arc_init_table('NAME_SKOV', 1);
execute procedure sp_sync_arc_init_table('OPER_DNI', 1);
execute procedure sp_sync_arc_init_table('OTCHET', 1);
execute procedure sp_sync_arc_init_table('OTCHET_SCH', 1);
execute procedure sp_sync_arc_init_table('PACHK', 1);
execute procedure sp_sync_arc_init_table('PARAM', 1);
execute procedure sp_sync_arc_init_table('PLACES', 1);
execute procedure sp_sync_arc_init_table('POLZ_SCH', 1);
execute procedure sp_sync_arc_init_table('PROC_ST', 1);
execute procedure sp_sync_arc_init_table('RAZD_BAL', 1);
execute procedure sp_sync_arc_init_table('RAZD_BALS', 1);
execute procedure sp_sync_arc_init_table('REMOTECLIENTS', 1, 'RC_PREPARESESSION;RC_LASTSESSION;RC$POINTER;RC_KRED_POINTER;');
execute procedure sp_sync_arc_init_table('REMOTECLIENTSCHETS', 1);
--execute procedure sp_sync_arc_init_table('REMOTECLIENTSCHETS_VB', 1);
execute procedure sp_sync_arc_init_table('REPORTS', 1);
execute procedure sp_sync_arc_init_table('RESTDESC', 1);
execute procedure sp_sync_arc_init_table('SCHET', 1, 'SCH_OST;SCH_DPP;');
execute procedure sp_sync_arc_init_table('SCHET_VB', 1, 'SCH_OST;SCH_DPP;');
execute procedure sp_sync_arc_init_table('SCH_CTL', 1);
execute procedure sp_sync_arc_init_table('SCH_DOX_DESCR', 1);
execute procedure sp_sync_arc_init_table('SCH_DOX_RAS_DESC', 1);
execute procedure sp_sync_arc_init_table('SCH_DOX_RAS_ID', 1);
execute procedure sp_sync_arc_init_table('SCH_KEY_EXT', 1);
execute procedure sp_sync_arc_init_table('SCH_OBSL', 1);
execute procedure sp_sync_arc_init_table('SCH_OPEN_SCHEMA', 1);
execute procedure sp_sync_arc_init_table('SEARCHCONDITIONS', 1);
execute procedure sp_sync_arc_init_table('SIMV_KP', 1);
execute procedure sp_sync_arc_init_table('SIMV_KP_BAZ', 1);
execute procedure sp_sync_arc_init_table('SMS_CONTRACT', 1);
execute procedure sp_sync_arc_init_table('SMS_MSG_STATE', 1);
execute procedure sp_sync_arc_init_table('SMS_PARAM', 1);
execute procedure sp_sync_arc_init_table('TIP_KL', 1);
execute procedure sp_sync_arc_init_table('UACL', 1);
execute procedure sp_sync_arc_init_table('UACL_SYSDESC', 1);
execute procedure sp_sync_arc_init_table('UGROUPS', 1);
execute procedure sp_sync_arc_init_table('UGROUPS_MEMBERS', 1);
execute procedure sp_sync_arc_init_table('USERRESTRICTIONS', 1);
execute procedure sp_sync_arc_init_table('USERS', 1);
execute procedure sp_sync_arc_init_table('USER_REPORTS', 1);
execute procedure sp_sync_arc_init_table('VALIDATIONS', 1);
execute procedure sp_sync_arc_init_table('VALUTA', 1);
execute procedure sp_sync_arc_init_table('VAL_B', 1);
execute procedure sp_sync_arc_init_table('VAL_KURS', 1);
execute procedure sp_sync_arc_init_table('VID_OBSL', 1);
execute procedure sp_sync_arc_init_table('VKLAD', 1);
execute procedure sp_sync_arc_init_table('XAR_SCH', 1);


